# -*- coding: utf-8 -*-

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Kw25uXTX1wp0_kcZnAjkLsV3A6bO09n
"""

import pandas as pd

"""# Entso G API

"""

url = 'https://transparency.entsog.eu/api/v1/operationalData.xlsx?forceDownload=true&pointDirection=de-tso-0009lng-00066entry&from=2023-01-01&to=2023-09-22&indicator=Physical%20Flow&periodType=day&timezone=CET&limit=-1&dataset=1&directDownload=true'

df = pd.read_excel(url, parse_dates=['periodTo', 'periodFrom']) # Lädt die URL in einen df

df.info()

df.iloc[0] # IntegerLocator: Zeige mir mal row [0] an

# Aufgabe: Grafik, die mit den Linienverlauf des LNG Imports anzeigt

df.plot.line(x='periodFrom', y='value')

#
url2 = 'https://transparency.entsog.eu/api/v1/operationalData.xlsx?forceDownload=true&pointDirection=de-tso-0017lng-00075entry&from=2023-01-01&to=2023-09-22&indicator=Physical%20Flow&periodType=day&timezone=CET&limit=-1&dataset=1&directDownload=true'
url3 = 'https://transparency.entsog.eu/api/v1/operationalData.xlsx?forceDownload=true&pointDirection=de-tso-0005lng-00060entry&from=2023-01-01&to=2023-09-22&indicator=Physical%20Flow&periodType=day&timezone=CET&limit=-1&dataset=1&directDownload=true'
df2 = pd.read_excel(url2, parse_dates=['periodTo', 'periodFrom']) # Lädt die URL in einen df
df3 = pd.read_excel(url3, parse_dates=['periodTo', 'periodFrom']) # Lädt die URL in einen df

dfgesamt = pd.concat([df,df2,df3])

dfpivot = dfgesamt.pivot_table(index='periodFrom', columns='pointLabel', values='value', aggfunc='max')

dfpivot.plot.area(legend=False)

dfgesamt.to_csv('gasimporte.csv')
